import React, { useEffect, useRef, useState } from "react";
import * as d3 from "d3";
import neighborhoodData from "./data/neighborhood.geojson";
import streetsData from "./data/geobase.json";
import placesData from "./data/donors.json";
import starIcon from "./data/star-svgrepo-com.svg";

function Sidebar({ location, onClose }) {
  if (!location) return null;

  return (
    <div className="h-full bg-black shadow-2xl overflow-auto">
      <div className="p-6">
        <div className="flex justify-between items-start mb-4">
          <h2 className="text-2xl font-bold text-white">{location.name}</h2>
          <button
            onClick={onClose}
            className="text-white hover:text-gray-300 text-3xl leading-none -mt-1"
          >
            ×
          </button>
        </div>
        <div className="space-y-4">
          <p className="text-gray-300 leading-relaxed">
            {location.description ||
              "This historic location played a significant role in the community. Visitors can explore the site and learn about its cultural importance and the events that took place here."}
          </p>
          <div className="pt-4 border-t border-gray-700">
            <p className="text-gray-400 text-sm">
              Location: {location.location[1].toFixed(4)},{" "}
              {location.location[0].toFixed(4)}
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}

function Map({ width, height }) {
  const containerRef = useRef(null);
  const tooltipRef = useRef(null);
  const baseWidth = 1200; // Fixed base dimensions
  const baseHeight = 800;
  const [selectedLocation, setSelectedLocation] = useState(null);
  const sidebarWidth = 320; // 80 * 4 = 320px (w-80 in Tailwind)

  useEffect(() => {
    // Ensure the container is available before initializing the SVG -- react creates the ref asynchronously, so we need to check if it's ready
    if (!containerRef.current) return;

    // Only initialize once!
    // this part looks for the svg element inside the containerRef. If it finds one, it means the map has already been initialized, so it returns early and prevents re-initialization.
    // This is important because useEffect can run multiple times (e.g., on re-renders), and we don't want to create multiple SVG elements or duplicate the map rendering.
    const existingSvg = d3.select(containerRef.current).select("svg");
    if (!existingSvg.empty()) return; // Already initialized

    // Create SVG with fixed viewBox and responsive dimensions
    // This creates an SVG element inside the containerRef with a fixed viewBox of 1200x800.
    // The width and height are set to 100% to make it responsive, and CSS styles ensure it scales properly while maintaining the aspect ratio.
    const svg = d3
      .select(containerRef.current)
      .append("svg")
      .attr("viewBox", [0, 0, baseWidth, baseHeight])
      .attr("width", "100%")
      .attr("height", "100%")
      .attr("style", "max-width: 100%; height: auto;");

    const tooltip = d3.select(tooltipRef.current);

    // this part is creating the map projection and path generator.
    // The projection is set to geoMercator, which is a common projection for world maps.
    // The fitSize method is used to automatically scale and position the map to fit within the specified dimensions (baseWidth and baseHeight) while maintaining the aspect ratio.
    // The path generator is then created using the defined projection, which will be used to convert GeoJSON data into SVG path elements for rendering the map.
    const projection = d3
      .geoMercator()
      .fitSize([baseWidth / 1.2, baseHeight / 1.2], streetsData);

    // Create a path generator using the defined projection. The path generator is a function that takes GeoJSON data and converts it into SVG path data (the "d" attribute of <path> elements).
    const path = d3.geoPath().projection(projection);

    // organizing the SVG elements into groups for better structure and easier manipulation.
    // The content group serves as a container for all map-related elements, while the mapGroup is specifically for the street paths.
    // This allows us to easily manage and style different parts of the map separately, such as adding location markers in a different group without affecting the street paths.
    const zoomGroup = svg.append("g").attr("class", "zoom-group");

    const content = zoomGroup.append("g").attr("id", "content");
    const mapGroup = content.append("g").attr("class", "map");

    // Draw streets
    // The select, data, and join pattern is used to bind the GeoJSON street data to SVG path elements.
    // For each feature in the streetsData, a path element is created with the "d" attribute generated by the path generator.
    // The stroke and fill styles are set to create a red outline for the streets without any fill color.
    mapGroup
      .selectAll("path")
      .data(streetsData.features)
      .join("path")
      .attr("d", path)
      .style("stroke", "red")
      .style("fill", "none")
      .style("stroke-width", 1);

    // Draw location markers
    const locationsGroup = content.append("g").attr("class", "locations");

    const markerData = [];

    placesData.locations.forEach((data) => {
      const loc = data.location;
      // adding each location at the appropriate position on the map by using the projection function to convert geographic coordinates (latitude and longitude) into pixel coordinates for placing the markers.
      const position = projection(loc);
      markerData.push({ x: position[0], y: position[1], data });

      const starGroup = locationsGroup
        .append("g")
        .attr("class", "location-marker")
        .attr(
          "transform",
          `translate(${projection(loc)[0]}, ${projection(loc)[1]})`,
        )
        // making the style of the location markers interactive by changing the cursor to a pointer when hovering over them,
        // indicating that they are clickable and can trigger events such as displaying tooltips or opening a sidebar with more information about the location.
        .style("cursor", "pointer")
        .datum({ x: position[0], y: position[1] });

      // this just gives each location a strar icon by appending an image element to the starGroup
      starGroup
        .append("image")
        .attr("class", "figures")
        .attr("href", starIcon)
        .attr("width", 30)
        .attr("height", 30)
        .attr("x", -15)
        .attr("y", -15);

      // Hover effects with DOM tooltip
      // when the mouse hovers over it will enlarge the star icon and display a tooltip with the location's name.
      starGroup.on("mouseenter", function (event) {
        d3.select(this)
          .select("image")
          .transition()
          .duration(200)
          .attr("width", 40)
          .attr("height", 40)
          .attr("x", -20)
          .attr("y", -20);

        // Show DOM tooltip
        // The tooltip is positioned near the mouse cursor using the event's pageX and pageY properties, and its text content is set to the name of the location.
        // this can be further styled with CSS to create a visually appealing tooltip that provides additional information about the location when the user hovers over the marker.
        tooltip
          .style("opacity", 1)
          .style("left", event.pageX + 15 + "px")
          .style("top", event.pageY - 35 + "px")
          .text(data.name);
      });

      // This part ensures that the tooltip follows the mouse cursor as it moves while hovering over the location marker.
      starGroup.on("mousemove", function (event) {
        tooltip
          .style("left", event.pageX + 15 + "px")
          .style("top", event.pageY - 35 + "px");
      });

      // when the mouse leaves the location marker, the star icon returns to its original size and the tooltip is hidden by setting its opacity back to 0.
      starGroup.on("mouseleave", function () {
        d3.select(this)
          .select("image")
          .transition()
          .duration(200)
          .attr("width", 30)
          .attr("height", 30)
          .attr("x", -15)
          .attr("y", -15);

        tooltip.style("opacity", 0);
      });
      // Click handler
      starGroup.on("click", function (event) {
        event.stopPropagation();
        setSelectedLocation(data);
      });
    });
    const zoom = d3
      .zoom()
      .scaleExtent([1, 8])
      .wheelDelta((event) => -event.deltaY * 0.01)
      .on("zoom", (event) => {
        const { transform } = event;

        zoomGroup.attr("transform", transform);

        // Now the function(d) correctly accesses the datum
        locationsGroup
          .selectAll(".location-marker")
          .attr("transform", function (d) {
            // d is the datum we attached: { x: ..., y: ... }
            return `translate(${d.x}, ${d.y}) scale(${1 / transform.k})`;
          });

        mapGroup.selectAll("path").style("stroke-width", 1 / transform.k);
      });

    svg.call(zoom);
  }, []);

  return (
    <div className="relative w-full h-screen bg-white flex flex-row gap-8 p-8 overflow-hidden">
      {/* DOM Tooltip */}
      <div
        ref={tooltipRef}
        className="absolute pointer-events-none bg-white border border-gray-300 rounded px-3 py-2 shadow-lg text-sm font-semibold text-gray-800 opacity-0 transition-opacity duration-200 z-50"
        style={{ whiteSpace: "nowrap" }}
      />

      {/* Map Container */}
      <div ref={containerRef} className="w-4/5 h-full" />

      {/* Sidebar */}
      <div
        className={`bg-red-500 transition-all duration-300 ease-in-out shadow-2xl overflow-hidden flex-shrink-0 ${
          selectedLocation ? "w-80" : "w-0"
        }`}
      >
        {selectedLocation && (
          <Sidebar
            location={selectedLocation}
            onClose={() => setSelectedLocation(null)}
          />
        )}
      </div>
    </div>
  );
}

export default Map;
